apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tensorflow-client
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
      - image: gcr.io/fit-stream-305821/tfclient
        env:
          - name: K_SINK
            value: ""
          - name: SHEET_ID
            value: ""
          - name: GOOGLE_CREDENTIALS_JSON
            value: |-
            {

            }