apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: dce
spec:
 template:
  spec:
   containers:
    - image:
      env:
        - name: K_SINK
          value: 
        - name: AWS_ACCESS_KEY
          value: 
        - name: AWS_SECRET_KEY
          value: 
        - name: AWS_REGION
          value: 
        - name: TENSORFLOW_ENDPOINT
          value: 